### ISSUE TITLE
[Feature Request] Darkmode, footer, meta (seo).

### ISSUE THREAD

**Issue by MartijnLindeman** [Molunerfinn/hexo-theme-melody#324]
## I want to create a new issue  

- [x] Yes, I have read [FAQ](https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/FAQ.md).
- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [x] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this did not help me.

## Feature Request

1. Adding a Darkmode button/switch in navv bar or footer option.
2. Option to add multiple footer urls, example: https://gyazo.com/c6c492795cbdea620f0a396bd2effcab
3. Being able to add social icons in footer would be a nice option. 
4. Meta tags / social card preview, example: 
A) current: https://gyazo.com/c1a08f8e8191445be9dd2d89ada35fd2
B) requested feature: https://gyazo.com/5f3b21a50f2d412e738ef1306775edb0
5. Multiple favicon options Example: https://gyazo.com/ef36e2a8fd7f41d43c8add7cdf62bb09

@myl7 
Thank you.
